variables:
  CI_IMAGE: "registry.gitlab.com/sophiebot/sophie-ci/sophie-ci:main"

default:
  interruptible: true

stages:
  - test
  - build
  - deploy

include:
  - '/build/bot-test.yml'
  - '/build/renovate.yml'
  - "/build/runtime/build.yml"
  - "/deploy/ci_staging.yml"
  - "/deploy/ci_prod.yml"
