variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  BRANCH: "$CI_COMMIT_BRANCH"

deploy_prod_beta:
  stage: deploy
  needs:
    - job: build_runtime_container
      optional: true
  image: willhallonline/ansible:2.18.6-alpine-3.18
  before_script:
    - cp $SSHKEY /tmp/sshkey
    - chmod 600 /tmp/sshkey
  script:
    - ansible-playbook -i "$ANSIBLE_INV" deploy/beta.yml --limit sprod
  environment:
    name: prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH == "beta" || $CI_COMMIT_BRANCH == "test_ci" || $CI_COMMIT_BRANCH == "test-ci"
      when: manual


deploy_prod_stable:
  stage: deploy
  needs:
    - job: build_runtime_container
      optional: true
  image: willhallonline/ansible:2.18.6-alpine-3.18
  before_script:
    - cp $SSHKEY /tmp/sshkey
    - chmod 600 /tmp/sshkey
  script:
    - ansible-playbook -i "$ANSIBLE_INV" deploy/stable.yml --limit sprod
  environment:
    name: prod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH == "stable" || $CI_COMMIT_BRANCH == "test_ci" || $CI_COMMIT_BRANCH == "test-ci"
      when: manual
