/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiCacheRouteImport } from './routes/ai-cache'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MongoRouteImport } from './routes/mongo'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as RedisRouteImport } from './routes/redis'
import { Route as TelegramRouteImport } from './routes/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCacheRoute = AiCacheRouteImport.update({
  id: '/ai-cache',
  path: '/ai-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MongoRoute = MongoRouteImport.update({
  id: '/mongo',
  path: '/mongo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisRoute = RedisRouteImport.update({
  id: '/redis',
  path: '/redis',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-cache': typeof AiCacheRoute
  '/logs': typeof LogsRoute
  '/mongo': typeof MongoRoute
  '/performance': typeof PerformanceRoute
  '/redis': typeof RedisRoute
  '/telegram': typeof TelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-cache': typeof AiCacheRoute
  '/logs': typeof LogsRoute
  '/mongo': typeof MongoRoute
  '/performance': typeof PerformanceRoute
  '/redis': typeof RedisRoute
  '/telegram': typeof TelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-cache': typeof AiCacheRoute
  '/logs': typeof LogsRoute
  '/mongo': typeof MongoRoute
  '/performance': typeof PerformanceRoute
  '/redis': typeof RedisRoute
  '/telegram': typeof TelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-cache'
    | '/logs'
    | '/mongo'
    | '/performance'
    | '/redis'
    | '/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-cache'
    | '/logs'
    | '/mongo'
    | '/performance'
    | '/redis'
    | '/telegram'
  id:
    | '__root__'
    | '/'
    | '/ai-cache'
    | '/logs'
    | '/mongo'
    | '/performance'
    | '/redis'
    | '/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCacheRoute: typeof AiCacheRoute
  LogsRoute: typeof LogsRoute
  MongoRoute: typeof MongoRoute
  PerformanceRoute: typeof PerformanceRoute
  RedisRoute: typeof RedisRoute
  TelegramRoute: typeof TelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-cache': {
      id: '/ai-cache'
      path: '/ai-cache'
      fullPath: '/ai-cache'
      preLoaderRoute: typeof AiCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mongo': {
      id: '/mongo'
      path: '/mongo'
      fullPath: '/mongo'
      preLoaderRoute: typeof MongoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis': {
      id: '/redis'
      path: '/redis'
      fullPath: '/redis'
      preLoaderRoute: typeof RedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCacheRoute: AiCacheRoute,
  LogsRoute: LogsRoute,
  MongoRoute: MongoRoute,
  PerformanceRoute: PerformanceRoute,
  RedisRoute: RedisRoute,
  TelegramRoute: TelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
