/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/actions/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Action */
        post: operations["prepare_action_api_v1_actions_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action */
        get: operations["get_action_api_v1_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/{action_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Action */
        post: operations["execute_action_api_v1_actions__action_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-cache/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Pricing */
        get: operations["ai_pricing_api_v1_ai_cache_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-cache/{chat_tid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Cache */
        get: operations["ai_cache_api_v1_ai_cache__chat_tid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_v1_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_events__seq__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mongo/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mongo Collections */
        get: operations["mongo_collections_api_v1_mongo_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mongo/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mongo Query */
        post: operations["mongo_query_api_v1_mongo_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/redis/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redis Query */
        post: operations["redis_query_api_v1_redis_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resources */
        get: operations["get_resources_api_v1_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate Browser */
        post: operations["authenticate_browser_api_v1_session_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart Worker */
        post: operations["restart_worker_api_v1_worker_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionExecuteRequest */
        ActionExecuteRequest: {
            /** Confirmation Text */
            confirmation_text: string;
            /** Run Id */
            run_id: string;
        };
        /** ActionPrepareResponse */
        ActionPrepareResponse: {
            /** Action Id */
            action_id: string;
            /** Confirmation Text */
            confirmation_text: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Operation */
            operation: string;
            preview: components["schemas"]["JsonValue"];
            /** Run Id */
            run_id: string;
            /** Target */
            target: string;
            /** Warnings */
            warnings: string[];
        };
        /** ActionStatusResponse */
        ActionStatusResponse: {
            /** Action Id */
            action_id: string;
            error?: components["schemas"]["ApiErrorDetail"] | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Operation */
            operation: string;
            result?: components["schemas"]["JsonValue"];
            /** Run Id */
            run_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "prepared" | "running" | "succeeded" | "failed" | "unknown" | "expired";
            /** Status Url */
            status_url: string;
            /** Target */
            target: string;
        };
        /** AiCacheClearAction */
        AiCacheClearAction: {
            /**
             * Cache Kind
             * @enum {string}
             */
            cache_kind: "messages" | "tools" | "context" | "pricing";
            /** Chat Tid */
            chat_tid?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ai_cache.clear";
        };
        /** AiCacheResponse */
        AiCacheResponse: {
            /** Configured Ttl Seconds */
            configured_ttl_seconds: number;
            /** Count */
            count: number;
            /** Entries */
            entries: components["schemas"]["JsonValue"][];
            /** Has More */
            has_more: boolean;
            /** Invalid Entries */
            invalid_entries: components["schemas"]["JsonValue"][];
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "messages" | "tools";
            /**
             * Media Transcription Cache
             * @default false
             * @constant
             */
            media_transcription_cache: false;
            /** Next Cursor */
            next_cursor?: number | null;
            /** Offset */
            offset?: number | null;
            /**
             * Provider Prompt Cache
             * @default not_reported
             * @constant
             */
            provider_prompt_cache: "not_reported";
            /** Replay Status */
            replay_status?: "not_evaluated" | null;
            /** Run Id */
            run_id: string;
            /**
             * Separate Response Cache
             * @default false
             * @constant
             */
            separate_response_cache: false;
            /** Truncated */
            truncated: boolean;
            /** Ttl */
            ttl: number;
        };
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ApiErrorDetail"];
        };
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Status Url */
            status_url?: string | null;
        };
        /** Base64RedisBytes */
        Base64RedisBytes: {
            /** Base64 */
            base64: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "mongo" | "redis" | "telegram" | "ai_cache" | "middleware" | "resource" | "log" | "process";
        /** EventSummary */
        EventSummary: {
            category: components["schemas"]["Category"];
            /** Chat Tid */
            chat_tid: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Type */
            error_type: string | null;
            level: components["schemas"]["Level"];
            /** Monotonic Ns */
            monotonic_ns: string;
            /** Name */
            name: string;
            origin: components["schemas"]["Origin"];
            outcome: components["schemas"]["Outcome"] | null;
            /** Parent Span Id */
            parent_span_id: string | null;
            phase: components["schemas"]["Phase"];
            /** Pid */
            pid: number;
            /** Redacted */
            redacted: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Seq */
            seq: number;
            /** Session Id */
            session_id: string;
            /** Span Id */
            span_id: string | null;
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Trace Id */
            trace_id: string | null;
            /** Truncated */
            truncated: boolean;
            /** Update Id */
            update_id: number | null;
        };
        /** EventsResponse */
        EventsResponse: {
            /** Dropped Total */
            dropped_total: number;
            /** Events */
            events: components["schemas"]["EventSummary"][];
            /** Gap */
            gap: boolean;
            /** Latest Seq */
            latest_seq: number | null;
            /** Next After */
            next_after: number;
            /** Oldest Seq */
            oldest_seq: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /**
         * Level
         * @enum {string}
         */
        Level: "debug" | "info" | "warning" | "error";
        /** MongoCollectionsResponse */
        MongoCollectionsResponse: {
            /** Collections */
            collections: string[];
            /** Run Id */
            run_id: string;
        };
        /** MongoDeleteAction */
        MongoDeleteAction: {
            _id: components["schemas"]["JsonValue"];
            /** Collection */
            collection: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mongo.delete_one";
        };
        /** MongoInsertAction */
        MongoInsertAction: {
            /** Collection */
            collection: string;
            /** Document */
            document: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mongo.insert_one";
        };
        /** MongoQueryRequest */
        MongoQueryRequest: {
            /** Collection */
            collection: string;
            /** Filter */
            filter?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /** Projection */
            projection?: {
                [key: string]: 0 | 1;
            } | null;
            /**
             * Skip
             * @default 0
             */
            skip: number;
            /** Sort */
            sort?: [
                string,
                -1 | 1
            ][];
        };
        /** MongoQueryResponse */
        MongoQueryResponse: {
            /** Duration Ms */
            duration_ms: number;
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["JsonValue"][];
            /** Run Id */
            run_id: string;
            /** Truncated */
            truncated: boolean;
        };
        /** MongoUpdateAction */
        MongoUpdateAction: {
            _id: components["schemas"]["JsonValue"];
            /** Collection */
            collection: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mongo.update_one";
            /** Update */
            update: {
                [key: string]: {
                    [key: string]: components["schemas"]["JsonValue"];
                };
            };
        };
        /**
         * Origin
         * @enum {string}
         */
        Origin: "startup" | "update" | "background" | "debugger";
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "ok" | "error" | "cancelled";
        /**
         * Phase
         * @enum {string}
         */
        Phase: "start" | "finish" | "instant";
        /** PricingCacheResponse */
        PricingCacheResponse: {
            invalid_entry: components["schemas"]["JsonValue"];
            /** Key */
            key: string;
            /**
             * Kind
             * @constant
             */
            kind: "pricing";
            /** Missing */
            missing: boolean;
            /** Run Id */
            run_id: string;
            /** Ttl */
            ttl: number;
            value: components["schemas"]["JsonValue"];
        };
        RedisBytes: string | components["schemas"]["Base64RedisBytes"];
        /** RedisCommandAction */
        RedisCommandAction: {
            /** Args */
            args: components["schemas"]["JsonValue"][];
            /**
             * Command
             * @enum {string}
             */
            command: "SET" | "DEL" | "UNLINK" | "HSET" | "HDEL" | "ZADD" | "ZREM" | "EXPIRE" | "PERSIST";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "redis.command";
        };
        /** RedisHashQuery */
        RedisHashQuery: {
            /**
             * Cursor
             * @default 0
             */
            cursor: number;
            key: components["schemas"]["RedisBytes"];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "hash";
        };
        /** RedisListQuery */
        RedisListQuery: {
            key: components["schemas"]["RedisBytes"];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "list";
        };
        /** RedisQueryResponse */
        RedisQueryResponse: {
            data: components["schemas"]["JsonValue"];
            /** Duration Ms */
            duration_ms: number;
            /** Has More */
            has_more: boolean;
            /** Length */
            length?: number | null;
            /**
             * Next Cursor
             * @description Redis cursor scans are live, non-atomic views; concurrent changes may move entries.
             */
            next_cursor: number;
            /** Run Id */
            run_id: string;
            /** Truncated */
            truncated: boolean;
            /** Ttl */
            ttl: number | null;
            /** Type */
            type: string;
        };
        /** RedisScanQuery */
        RedisScanQuery: {
            /**
             * Cursor
             * @default 0
             */
            cursor: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "scan";
            /** @default * */
            pattern: components["schemas"]["RedisBytes"];
        };
        /** RedisSetQuery */
        RedisSetQuery: {
            /**
             * Cursor
             * @default 0
             */
            cursor: number;
            key: components["schemas"]["RedisBytes"];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set";
        };
        /** RedisStringQuery */
        RedisStringQuery: {
            key: components["schemas"]["RedisBytes"];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "string";
        };
        /** RedisZsetQuery */
        RedisZsetQuery: {
            key: components["schemas"]["RedisBytes"];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "zset";
        };
        /** ResourceResponse */
        ResourceResponse: {
            /** Collector */
            collector: {
                [key: string]: unknown;
            }[];
            /** Run Id */
            run_id: string | null;
            /** Vite */
            vite: {
                [key: string]: unknown;
            }[];
            /** Worker */
            worker: {
                [key: string]: unknown;
            }[];
        };
        /** RestartResponse */
        RestartResponse: {
            /**
             * Status
             * @constant
             */
            status: "reloading";
        };
        /** SessionResponse */
        SessionResponse: {
            /** Capabilities */
            capabilities: {
                [key: string]: boolean | string | number;
            };
            /** Csrf Token */
            csrf_token: string;
            /** Detail */
            detail: string | null;
            /** Dropped Total */
            dropped_total: number;
            /** Event Bytes */
            event_bytes: number;
            /** Event Count */
            event_count: number;
            /** Latest Seq */
            latest_seq: number | null;
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Oldest Seq */
            oldest_seq: number | null;
            /** Recorder Errors */
            recorder_errors: number;
            /** Restart Required */
            restart_required: boolean;
            /** Run Id */
            run_id: string | null;
            /** Sanitized Targets */
            sanitized_targets: {
                [key: string]: string | number;
            };
            /**
             * Sensitive
             * @default true
             * @constant
             */
            sensitive: true;
            /** Session Id */
            session_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "ready" | "reloading" | "failed" | "stopped";
            /** Worker Pid */
            worker_pid: number | null;
        };
        /** StoredEvent */
        StoredEvent: {
            category: components["schemas"]["Category"];
            /** Chat Tid */
            chat_tid?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Type */
            error_type?: string | null;
            /** @default info */
            level: components["schemas"]["Level"];
            /** Monotonic Ns */
            monotonic_ns: string;
            /** Name */
            name: string;
            origin: components["schemas"]["Origin"];
            outcome?: components["schemas"]["Outcome"] | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            payload?: components["schemas"]["JsonValue"];
            phase: components["schemas"]["Phase"];
            /** Pid */
            pid: number;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Seq */
            seq: number;
            /** Session Id */
            session_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Summary */
            summary: string;
            /** Task Id */
            task_id?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Update Id */
            update_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    prepare_action_api_v1_actions_prepare_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MongoInsertAction"] | components["schemas"]["MongoUpdateAction"] | components["schemas"]["MongoDeleteAction"] | components["schemas"]["RedisCommandAction"] | components["schemas"]["AiCacheClearAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionPrepareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_api_v1_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_action_api_v1_actions__action_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionStatusResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    ai_pricing_api_v1_ai_cache_pricing_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingCacheResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_cache_api_v1_ai_cache__chat_tid__get: {
        parameters: {
            query?: {
                kind?: "messages" | "tools";
                offset?: number;
                cursor?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                chat_tid: number;
            };
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiCacheResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_v1_events_get: {
        parameters: {
            query?: {
                after?: number;
                before?: number | null;
                limit?: number;
                run_id?: string | null;
                category?: components["schemas"]["Category"] | null;
                trace_id?: string | null;
                chat_tid?: number | null;
                level?: components["schemas"]["Level"] | null;
                origin?: components["schemas"]["Origin"] | null;
                q?: string | null;
                min_duration_ms?: number | null;
                from_time?: string | null;
                to_time?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_events_stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__seq__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                seq: number;
            };
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mongo_collections_api_v1_mongo_collections_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MongoCollectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mongo_query_api_v1_mongo_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MongoQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MongoQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redis_query_api_v1_redis_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedisScanQuery"] | components["schemas"]["RedisStringQuery"] | components["schemas"]["RedisHashQuery"] | components["schemas"]["RedisSetQuery"] | components["schemas"]["RedisListQuery"] | components["schemas"]["RedisZsetQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedisQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resources_api_v1_resources_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authenticate_browser_api_v1_session_auth_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_worker_api_v1_worker_restart_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                sophie_debug_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
